name: 'Run LanguageTool with reviewdog'
description: '🐶 Run LanguageTool with reviewdog on pull requests to improve code review experience.'
author: 'haya14busa'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'
  ### Flags for reviewdog ###
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  reporter:
    description: 'Reporter of reviewdog command [github-pr-check,github-pr-review].'
    default: 'github-pr-check'
  ### Flags for target file ###
  patterns:
    description: 'Space separated target file glob patterns. https://github.com/haya14busa/ghglob'
    default: '**/*.md **/*.txt'
  ### Flags for LanguageTool ###
  # Ref: https://languagetool.org/http-api/swagger-ui/#!/default/post_check
  language:
    description: 'language of LanguageTool'
    default: 'en-US'
  enabled_rules:
    description: 'comma separated enabledRules of LanguageTool'
  disabled_rules:
    description: 'comma separated disabledRules of LanguageTool'
    default: 'WHITESPACE_RULE,EN_QUOTES,DASH_RULE,WORD_CONTAINS_UNDERSCORE,UPPERCASE_SENTENCE_START,ARROWS,COMMA_PARENTHESIS_WHITESPACE,UNLIKELY_OPENING_PUNCTUATION,SENTENCE_WHITESPACE,CURRENCY,EN_UNPAIRED_BRACKETS,PHRASE_REPETITION,PUNCTUATION_PARAGRAPH_END,METRIC_UNITS_EN_US,ENGLISH_WORD_REPEAT_BEGINNING_RULE'
  enabled_categories:
    description: 'comma separated enabledCategories of LanguageTool'
  disabled_categories:
    description: 'comma separated disabledCategories of LanguageTool'
    default: 'TYPOS,TYPOGRAPHY'
  enabled_only:
    description: 'enabledOnly of LanguageTool'
    default: 'false'
  custom_api_endpoint:
    description: 'Custom API endpoint of LanguageTool server. e.g. https://languagetool.org/api'
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'

# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: 'type'
  color: 'blue'
