name: "Run LanguageTool with reviewdog"
description: "🐶 Run LanguageTool with reviewdog on pull requests to improve code review experience."
author: "FluxNinja"
inputs:
  github_token:
    description: "GITHUB_TOKEN"
    default: "${{ github.token }}"
  ### Flags for reviewdog ###
  level:
    description: "Report level for reviewdog [info,warning,error]"
    default: "error"
  reporter:
    description: "Reporter of reviewdog command [github-pr-check,github-pr-review]."
    default: "github-pr-review"
  filter_mode:
    description: "filter mode for reviewdog"
    default: "file"
  ### Flags for target file ###
  patterns:
    description: "Space separated target file glob patterns. https://github.com/haya14busa/ghglob"
    default: "**/*.md **/*.txt"
  filter_files:
    description: "changed or all"
    default: "changed"
  ### Flags for LanguageTool ###
  # Ref: https://languagetool.org/http-api/swagger-ui/#!/default/post_check
  language:
    description: "language of LanguageTool"
    default: "en-US"
  enabled_rules:
    description: "comma separated enabledRules of LanguageTool"
  disabled_rules:
    description: "comma separated disabledRules of LanguageTool"
    default: ""
  enabled_categories:
    description: "comma separated enabledCategories of LanguageTool"
  disabled_categories:
    description: "comma separated disabledCategories of LanguageTool"
    default: ""
  enabled_only:
    description: "enabledOnly of LanguageTool"
    default: "false"
  api_endpoint:
    description: "API endpoint of LanguageTool server. e.g. https://languagetool.org/api"
    default: "https://languagetool.org/api"
  username:
    description: "Username"
    default: ""
  api_key:
    description: "API Key"
    default: ""
runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "type"
  color: "orange"
